apiVersion: v1
kind: ConfigMap
metadata:
  name: ec2crud-pipeline
  labels:
    jenkins-jenkins-config: "true"
data:
  test-pipeline.yaml: |+
    jobs:
      - script: >
         
          multibranchPipelineJob('crud-ec2') {
            branchSources {
                git {
                    id('9812873654')
                    remote('https://github.com/MiCh4n/crud-ec2')
                }
            }
            orphanedItemStrategy {
                discardOldItems {
                    numToKeep(20)
                }
            }
          }