apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pipeline
  labels:
    jenkins-jenkins-config: "true"
data:
  test-pipeline.yaml: |+
    jobs:
      - script: >
         
          multibranchPipelineJob('test') {
            branchSources {
                git {
                    id('123456789')
                    remote('https://github.com/MiCh4n/test')
                }
            }
            orphanedItemStrategy {
                discardOldItems {
                    numToKeep(20)
                }
            }
          }